name: Build and Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate version
        id: version
        run: echo "version=v$(date +'%Y.%m.%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
          path: ./dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: site.zip
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Release ${{ steps.version.outputs.version }}
            
            This release contains the built Vite application.
