name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
          path: ./dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: site.zip
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            
            This release contains the built Vite application.
